// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://antbykdmufaooxsnzsbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFudGJ5a2RtdWZhb294c256c2J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1MjQzNjUsImV4cCI6MjA5MDEwMDM2NX0.-bQYUtJlVSTggYVS7nptviHpEVfyiI3XVbiPHJHBR2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});